ADMIN_PASSWORD = "evbadmin"
EVS_URL = "https://everskill.streamlit.app"
EVI_ENABLED = false
EVI_URL = ""
ACCESS_WEBAPP_URL = "https://script.google.com/macros/s/AKfycbyR2P0L32XfMokbl7eBv7E35ms_3Sqtp9ZJVquxOGdmkd-CWxV2R2oP5YFuuoxBbM8/exec"

